### ISSUE TITLE
sizeof integertypes

### ISSUE THREAD

**Issue by BloodyWulf** [overflowerror/Serwer#1]
Hey there.

There can be a problem with the size of integertypes.

As Compiler you can take gcc or clang. You should add the compilerflag -Wextra to your Makefile.
File: webserver.c, Line 164 and Line 220.
> webserver.c:164:20: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
>         for (int i = 0; i < strlen(*path); i++) {
>                         ~ ^ ~~~~~~~~~~~~~
> webserver.c:220:19: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
>         for(int i = 0; i < strlen(buffer); i++) {
>                        ~ ^ ~~~~~~~~~~~~~~

What does this mean exactly?
My system is a 64bit system (close normal these days) and this means that int is in this case 32 bit but unsigned long is 64bit (strlen returns size_t aka unsigned long).
On a 32bit system unsigned long should be 32bit like int.

That the two types have different signs is another problem, see below.

So if the worst case occurs these lines will be endless loops.
Even worse, because int is signed, the overflow of an signed integer results in undefined behavior.

In this case you should choose the same type like the type that is returned by strlen(), here size_t instead of int.

Btw: On other platforms like AVR microcontrollers int is only 16bit and unsigned long is 32 bit.

Regards

**Comment by sigmasternchen** [comment]
That'a merely an aestetic point. If the strlen of buffer causes an signed integer overflow (= one line in the HTTP request header > 2 Gigs) that will cause other problems as well.

For the sake of beauty and speed, I'll change that to size_t.

BTW: On AVR you have a few KiB of RAM. 16 Bit signed int overflow is at about 32 KiB (2^15 * 8 Bit).

**Comment by BloodyWulf** [comment]
You should do this to write better, safer and reliable software. Nothing else.
This is one point where i would look at first if i would be an attacker.
There is one easy rule:
> **All input is evil until proven otherwise!**

Until you can not guarantee that an overflow will never ever happen you have to look about it. If there could be an signed-overflow you have to look two times about it, because it is undefined behavior. You have to avoid undefined behavior at any costs.

The argument about speed is funny. Let's look at the head of one of the mentioned loops:
`for(int i = 0; i < strlen(buffer); i++) {`
strlen will be called at **each** iteration. What do you think? Is the datatype that what make it slow or a function call, where the duration of the function depends of the len of the argument?

You should do it like this:
```
size_t buf_len = strlen(buffer);
for(size_t i = 0; i < buf_len; i++) {
```
That will increase the speed much more as any right or wrong datatypes will ever do it.

My mentioned about AVR was to make clear that you should never rely on platform specific width of datatypes. Your software is not portable.

BTW: On AVR you can not only operate at RAM you can also operate at the FLASH and there you have up to 256kB of memory. On ARM-Cortex M3 8bit, 16bit and 32bit integertypes will be treated all the same way, so there is no slow down.

You should look where you can get a real increasing of execution speed, like avoid strlen in the loophead. All other is microoptimization that will bring you not forward.

**Comment by sigmasternchen** [comment]
You got a point there.

Your example was misleading. I made a mistake, but not on the cost of portability. 

I don't know which µC you were using, but all AVR controllers I've ever used just had 512 bytes of EEPROM and the flash (16 KiB) was a read-only memory for the program (because of Harvard architecture).
On ARM-Cortex that might be true, but one of my professors ones told me that I should use int instead of short or char (= definition of int16_t and int8_t) except when it's necessary, because most processors can handle the native bus-width the fastest.
