### ISSUE TITLE
casting the result of malloc

### ISSUE THREAD

**Issue by BloodyWulf** [overflowerror/Serwer#2]
Hey there.

You shouldn't cast the result of malloc in C (in C++ you have to cast!). If you forget to include <stdlib.h> the cast can obfuscate warnings. If you forget to include <stdlib.h> the build-in malloc from the compiler will be used.

[Do I cast the result of malloc?](http://stackoverflow.com/a/605858)

Regards

**Comment by sigmasternchen** [comment]
Apparently there is more than one [opinion](http://stackoverflow.com/a/14879184) on this. 
Nevertheless I understand the reason why one should not cast.
